name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update Version
        run: python version.py
        # working-directory:

      - name: Read Version
        id: get_version
        run: echo ::set-output name=version::$(python version.py)

      - name: Set Version Environment Variable
        run: |
          echo "VERSION_OLD=${{ steps.get_version.outputs.version }}"
          echo "VERSION_OLD=${{ steps.get_version.outputs.version }}" >> $GITHUB_ENV

      - name: Set Version Environment Variable
        id: set_version
        run: |
          echo "VERSION_NEW=$(python version.py)"
          echo "VERSION_NEW=$(python version.py)" >> $GITHUB_ENV

      - name: Build application
        run: |
          pyinstaller --name DirectoryScanner app.py --onefile -w

      - name: Display DirectoryScanner
        run: |
          cd dist
          ls -R

      - name: Commit Version Update
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add version.txt
          git commit -m "Bump version to $(cat version.txt)"
          git push
        # working-directory:

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/DirectoryScanner.exe
          tag_name: v${{ env.VERSION_NEW }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
